---
- name: download packages(redhat7)
  include_tasks: packages-redhat7.yml
  when:
    - ansible_distribution_major_version == "7"
    - inventory_hostname in groups['rpm-redhat7']
    - download_option == "full" or download_option == "redhat7"

- name: download packages(redhat8)
  include_tasks: packages-redhat8.yml
  when:
    - ansible_distribution_major_version == "8"  
    - inventory_hostname in groups['rpm-redhat8']
    - download_option == "full" or download_option == "redhat8"

